spring:
  application:
    name: pomki
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pomki
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      username: 

server:
  port: 8080

logging:
  level:
    com.cooltomato.pomki: DEBUG
    org.springframework.data.redis: DEBUG

# JWT 설정
jwt:
  secret-key: pomki-secret-key-for-development-only-do-not-use-in-production
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 604800000  # 1주일

# OAuth2 설정 (개발용 - 실제 값은 별도 환경변수로 관리)
oauth2:
  google:
    client-id: your-google-client-id
    client-secret: your-google-client-secret
  kakao:
    client-id: your-kakao-client-id
    client-secret: your-kakao-client-secret

# AI 설정 (OpenAI API)
ai:
  openai:
    api-key: # OpenAI API 키를 여기에 입력하세요
    model: gpt-3.5-turbo 