spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pomki
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true 