spring:
  datasource:
    url: ${DB_URL-PROD}
    driver-class-name: ${DB_DRIVER-PROD}
    username: ${DB_USERNAME-PROD}
    password: ${DB_PASSWORD-PROD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: ${DB_PLATFORM-PROD}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true 